openapi: 3.0.3
info:
  title: Template
  version: '1.0'
components:
  schemas:
    MSDMNE_DMNMessage:
      type: object
      properties:
        kieBaseName:
          type: string
        column:
          format: int32
          type: integer
        id:
          format: int64
          type: integer
        level:
          $ref: '#/components/schemas/MSDMNE_Level'
        line:
          format: int32
          type: integer
        path:
          type: string
        text:
          type: string
        exception:
          type: object
        feelEvent:
          $ref: '#/components/schemas/MSDMNE_FEELEvent'
        message:
          type: string
        messageType:
          $ref: '#/components/schemas/MSDMNE_DMNMessageType'
        severity:
          $ref: '#/components/schemas/MSDMNE_Severity'
        sourceId:
          type: string
        sourceReference:
          type: object
    MSDMNE_Severity:
      enum:
        - ERROR
        - INFO
        - TRACE
        - WARN
      type: string
    MSDMNE_DMNMessageType:
      enum:
        - DECISION_NOT_FOUND
        - DECISION_TABLE_1STNFVIOLATION
        - DECISION_TABLE_2NDNFVIOLATION
        - DECISION_TABLE_ANALYSIS
        - DECISION_TABLE_ANALYSIS_EMPTY
        - DECISION_TABLE_ANALYSIS_ERROR
        - DECISION_TABLE_CONTRACTION_RULE
        - DECISION_TABLE_GAP
        - DECISION_TABLE_HITPOLICY_FIRST
        - DECISION_TABLE_HITPOLICY_RECOMMENDER
        - DECISION_TABLE_MASKED_RULE
        - DECISION_TABLE_MISLEADING_RULE
        - DECISION_TABLE_OVERLAP
        - DECISION_TABLE_OVERLAP_HITPOLICY_ANY
        - DECISION_TABLE_OVERLAP_HITPOLICY_UNIQUE
        - DECISION_TABLE_SUBSUMPTION_RULE
        - DMNDI_MISSING_DIAGRAM
        - DMNDI_UNKNOWN_REF
        - DUPLICATED_ITEM_DEF
        - DUPLICATED_PARAM
        - DUPLICATED_RELATION_COLUMN
        - DUPLICATE_NAME
        - ERROR_EVAL_NODE
        - ERR_COMPILING_FEEL
        - ERR_EVAL_CTX
        - EXPR_TYPE_NOT_SUPPORTED_IN_NODE
        - FAILED_VALIDATION
        - FAILED_VALIDATOR
        - FAILED_XML_VALIDATION
        - FEEL_EVALUATION_ERROR
        - ILLEGAL_USE_OF_NAME
        - ILLEGAL_USE_OF_TYPEREF
        - IMPORT_NOT_FOUND
        - INVALID_ATTRIBUTE_VALUE
        - INVALID_HREF_SYNTAX
        - INVALID_NAME
        - INVALID_SYNTAX
        - INVOCATION_ERROR
        - KIE_API
        - MISSING_EXPRESSION
        - MISSING_NAME
        - MISSING_OUTPUT_VALUES
        - MISSING_TYPE_REF
        - MISSING_VARIABLE
        - PARAMETER_MISMATCH
        - RELATION_CELL_COUNT_MISMATCH
        - RELATION_CELL_NOT_LITERAL
        - REQ_NOT_FOUND
        - TYPE_DEF_NOT_FOUND
        - TYPE_REF_NOT_FOUND
        - UNSUPPORTED_ELEMENT
        - VARIABLE_NAME_MISMATCH
      type: string
    MSDMNE_FEELEvent:
      type: object
      properties:
        column:
          format: int32
          type: integer
        line:
          format: int32
          type: integer
        message:
          type: string
        offendingSymbol:
          type: object
        severity:
          $ref: '#/components/schemas/MSDMNE_Severity1'
        sourceException:
          type: object
    MSDMNE_Severity1:
      enum:
        - ERROR
        - INFO
        - TRACE
        - WARN
      type: string
    MSDMNE_Level:
      enum:
        - ERROR
        - INFO
        - WARNING
      type: string
    MSDMNE_KogitoDMNDecisionResult:
      type: object
      properties:
        decisionId:
          type: string
        decisionName:
          type: string
        messages:
          type: array
          items:
            $ref: '#/components/schemas/MSDMNE_DMNMessage'
        result:
          type: object
        status:
          $ref: '#/components/schemas/MSDMNE_DecisionEvaluationStatus'
        evaluationStatus:
          $ref: '#/components/schemas/MSDMNE_DecisionEvaluationStatus'
    MSDMNE_DecisionEvaluationStatus:
      enum:
        - EVALUATING
        - FAILED
        - NOT_EVALUATED
        - SKIPPED
        - SUCCEEDED
      type: string
    MSDMNE_KogitoDMNResult:
      type: object
      properties:
        decisionResults:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/MSDMNE_KogitoDMNDecisionResult'
        dmnContext:
          type: object
          additionalProperties: {}
        messages:
          type: array
          items:
            $ref: '#/components/schemas/MSDMNE_DMNMessage'
        modelName:
          type: string
        namespace:
          type: string
